#theme: jekyll-theme-midnight
theme: minima
markdown: kramdown
timezone: Australia/Melbourne

title: ozzmosis.com
description: andrew clarke
show_excerpts: true

minima:
  date_format: "%a %Y-%m-%d %H:%M"

plugins:
  - jekyll-feed
